# Generated by Django 3.2.5 on 2024-09-02 21:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpnsessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع المصروف')),
            ],
        ),
        migrations.CreateModel(
            name='Expnsess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expnsess_date', models.DateField(default=datetime.date.today, verbose_name='التاريخ')),
                ('expnsess_amount', models.FloatField(default=0.0, verbose_name='قيمة المصروف')),
                ('expnsess_details', models.CharField(blank=True, max_length=200, null=True, verbose_name='وصف المصروف')),
                ('expnsess_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('expnsess_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.expnsesstype', verbose_name='بند المصروف')),
            ],
        ),
    ]
