# Generated by Django 3.2.5 on 2024-08-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_alter_sellerpayments_date'),
        ('Invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsellers', verbose_name='العميل'),
        ),
    ]
