# Generated by Django 3.2.5 on 2024-08-02 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0012_auto_20240802_2324'),
        ('Invoices', '0002_alter_invoice_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Wool.wool', verbose_name='الصنف'),
        ),
    ]
