# Generated by Django 3.2.5 on 2024-08-02 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_color'),
        ('Invoices', '0003_alter_invoiceitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='wool_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.color', verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='wool_weight',
            field=models.FloatField(default=0.0, verbose_name='الوزن'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.IntegerField(choices=[(1, 'قطعة')], default=0, verbose_name='الوحدة'),
        ),
    ]
