# Generated by Django 3.2.5 on 2024-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0004_auto_20240802_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='total_weight',
            field=models.FloatField(default=0.0, verbose_name='اجمالي الوزن'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.FloatField(default=0.0, verbose_name='اجمالي الحساب'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='wool_weight',
            field=models.FloatField(default=0.0, verbose_name='وزن الوحدة'),
        ),
    ]
