# Generated by Django 3.2.5 on 2024-08-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0005_auto_20240808_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='unit',
        ),
    ]
