# Generated by Django 3.2.5 on 2024-08-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoices', '0006_remove_invoiceitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='check_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الشيك '),
        ),
        migrations.AddField(
            model_name='invoice',
            name='check_value',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='قيمة الشيك'),
        ),
    ]
