# Generated by Django 3.2.5 on 2024-06-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم الهاتف')),
                ('customer_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='العنوان')),
                ('customer_id', models.CharField(blank=True, max_length=14, null=True, verbose_name='الرقم القومي')),
                ('initial_balance_debit', models.FloatField(default=0, verbose_name='القيمة الافتتاحية')),
                ('initial_balance_type', models.IntegerField(choices=[(1, 'للعميل'), (2, 'علي العميل')], default=0, verbose_name='نوع القيمة الافتتاحية')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('agreement', models.TextField(blank=True, null=True, verbose_name='اتفاق مسبق')),
            ],
        ),
    ]
