# Generated by Django 3.2.5 on 2024-02-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woolsupplierquantity',
            name='wool_color',
            field=models.CharField(default='#FFFFFF', max_length=50, verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='woolsupplierquantity',
            name='wool_company',
            field=models.CharField(default='MC', max_length=50, verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='woolsupplierquantity',
            name='wool_number',
            field=models.IntegerField(default=30, verbose_name='رقم نوع الخامة..مثال:30-24...'),
        ),
        migrations.AlterField(
            model_name='woolsupplierquantity',
            name='wool_type',
            field=models.IntegerField(choices=[(1, 'قطن'), (2, 'صوف'), (3, 'عجينة'), (4, 'سبن'), (5, 'لكرة'), (6, 'رمش'), (7, 'عصب'), (8, 'بلستر'), (9, 'استك')], verbose_name='نوع الخامة'),
        ),
    ]
