# Generated by Django 3.2.5 on 2024-02-11 00:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wool', '0002_auto_20240207_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woolsupplierquantity',
            name='wool_company',
        ),
        migrations.RemoveField(
            model_name='woolsupplierquantity',
            name='wool_number',
        ),
        migrations.RemoveField(
            model_name='woolsupplierquantity',
            name='wool_type',
        ),
        migrations.AlterField(
            model_name='woolsupplierquantity',
            name='wool_color',
            field=models.CharField(default='', max_length=50, verbose_name='اللون'),
        ),
        migrations.CreateModel(
            name='Wool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wool_created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('wool_date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('wool_name', models.CharField(max_length=50, verbose_name='اسم الخامه')),
                ('wool_type', models.IntegerField(choices=[(1, 'قطن'), (2, 'صوف'), (3, 'عجينة'), (4, 'سبن'), (5, 'لكرة'), (6, 'رمش'), (7, 'عصب'), (8, 'بلستر'), (9, 'استك')], verbose_name='نوع الخامة')),
                ('wool_company', models.CharField(max_length=50, verbose_name='الشركة')),
                ('wool_number', models.IntegerField(verbose_name='رقم نوع الخامة...')),
                ('wool_user_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
            ],
        ),
        migrations.AddField(
            model_name='woolsupplierquantity',
            name='wool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Wool.wool', verbose_name='الخامة'),
            preserve_default=False,
        ),
    ]
