# Generated by Django 3.2.5 on 2024-02-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_color'),
        ('Wool', '0004_alter_woolsupplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woolsupplierquantity',
            name='wool_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.color', verbose_name='اللون'),
        ),
    ]
