# Generated by Django 3.2.5 on 2024-03-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0006_alter_wool_wool_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='woolsupplierquantity',
            name='wool_item_count',
            field=models.FloatField(default=0.0, verbose_name='عدد الشكاير'),
        ),
    ]
