# Generated by Django 3.2.5 on 2024-03-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0007_woolsupplierquantity_wool_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wool',
            name='wool_created_date',
        ),
    ]
