# Generated by Django 3.2.5 on 2024-08-02 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0011_auto_20240617_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woolsupplier',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='woolsupplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wool.woolsupplier', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='woolsupplierquantity',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wool.woolsupplier', verbose_name='الشركة'),
        ),
    ]
