# Generated by Django 3.2.5 on 2024-08-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0012_auto_20240802_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wool',
            name='wool_company',
        ),
        migrations.AddField(
            model_name='wool',
            name='wool_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن الخامة...'),
        ),
    ]
