# Generated by Django 3.2.5 on 2024-08-02 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0013_auto_20240803_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='woolsupplierquantity',
            name='wool_price',
        ),
        migrations.AddField(
            model_name='woolsupplierquantity',
            name='wool_loat_number',
            field=models.FloatField(default=0.0, verbose_name='رقم اللوط'),
        ),
        migrations.AlterField(
            model_name='woolsupplierpayment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wool.woolsupplier', verbose_name='التاجر'),
        ),
        migrations.AlterField(
            model_name='woolsupplierquantity',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wool.woolsupplier', verbose_name='التاجر'),
        ),
    ]
