# Generated by Django 3.2.5 on 2024-08-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0014_auto_20240803_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='woolsupplierquantity',
            name='total_weight',
            field=models.FloatField(default=0.0, verbose_name='اجمالي الوزن'),
        ),
    ]
