# Generated by Django 3.2.5 on 2024-08-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0015_woolsupplierquantity_total_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woolsupplierquantity',
            name='wool_loat_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم اللوط'),
        ),
    ]
