# Generated by Django 3.2.5 on 2024-08-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_color'),
        ('Wool', '0016_alter_woolsupplierquantity_wool_loat_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WoolOperatoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('operation_type', models.IntegerField(choices=[(1, 'دخول عن طريق مورد'), (2, 'خروج كمية لفاتورة مبيعات'), (3, 'دخول مرتجع للمخزن'), (4, 'حذف كمية بشكل يدوي')], verbose_name='نوع العملية')),
                ('operation_count', models.FloatField(default=0.0, verbose_name='الكمية')),
                ('operation_total_weight', models.FloatField(default=0.0, verbose_name='اجمالي الوزن')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('operation_wool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wool.wool', verbose_name='الخامة')),
                ('operatoin_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.color', verbose_name='اللون')),
            ],
        ),
    ]
