# Generated by Django 3.2.5 on 2024-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0017_wooloperatoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wooloperatoin',
            name='operation_total_price',
            field=models.FloatField(default=0.0, verbose_name='اجمالي الحساب'),
        ),
    ]
