# Generated by Django 3.2.5 on 2024-08-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0018_wooloperatoin_operation_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wooloperatoin',
            old_name='operatoin_color',
            new_name='operation_color',
        ),
    ]
