# Generated by Django 3.2.5 on 2024-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0020_wooloperatoin_operation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='woolsupplierquantity',
            name='wool_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='السعر'),
        ),
    ]
