# Generated by Django 3.2.5 on 2024-06-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wool', '0008_remove_wool_wool_created_date'),
        ('Core', '0002_color'),
        ('Factories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryoutside',
            name='wool_type',
        ),
        migrations.AddField(
            model_name='factoryoutside',
            name='wool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Wool.wool', verbose_name='الخامة'),
        ),
        migrations.AlterField(
            model_name='factoryoutside',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.color', verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=50, verbose_name='الاسم'),
        ),
    ]
