# Generated by Django 3.2.5 on 2024-06-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Factories', '0002_auto_20240609_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryoutside',
            name='wool_count_item',
            field=models.FloatField(default=1, verbose_name='عدد الشكاير'),
            preserve_default=False,
        ),
    ]
