# Generated by Django 3.2.5 on 2024-06-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_color'),
        ('Factories', '0003_factoryoutside_wool_count_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryinside',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.color', verbose_name='اللون'),
        ),
    ]
