# Generated by Django 3.2.5 on 2024-07-20 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0017_alter_sellerpayments_date'),
        ('Factories', '0004_alter_factoryinside_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('item_count', models.FloatField(verbose_name='العدد')),
                ('item_price', models.FloatField(verbose_name='سعر القطعة')),
                ('total_price', models.FloatField(verbose_name='اجمالي السعر')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('returned_details', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Factories.factory', verbose_name='المصنع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='الموديل')),
            ],
        ),
    ]
