# Generated by Django 3.2.5 on 2024-07-24 23:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_color'),
        ('Products', '0018_alter_sellerpayments_date'),
        ('Factories', '0005_factoryreturned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantityInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('product_count', models.IntegerField(blank=True, null=True, verbose_name='الكمية')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('factory_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Factories.factory', verbose_name='المصنع')),
                ('product_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.color', verbose_name='اللون')),
                ('product_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.product', verbose_name='الموديل')),
            ],
        ),
    ]
