# Generated by Django 3.2.5 on 2024-08-08 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0026_auto_20240808_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 18, 54, 31, 496282, tzinfo=utc), verbose_name='تاريخ الحضور'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 18, 54, 31, 497251, tzinfo=utc), verbose_name='تاريخ السحب'),
        ),
        migrations.AlterField(
            model_name='workerproduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 8, 18, 54, 31, 497968, tzinfo=utc), verbose_name='تاريخ الاستلام'),
        ),
    ]
