# Generated by Django 3.2.5 on 2024-02-07 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 5, 49, 52, 534055), verbose_name='التاريخ'),
        ),
    ]
