# Generated by Django 3.2.5 on 2024-02-11 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 2, 56, 13, 804549), verbose_name='التاريخ'),
        ),
    ]
