# Generated by Django 3.2.5 on 2024-02-12 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 15, 23, 1, 834453), verbose_name='التاريخ'),
        ),
    ]
