# Generated by Django 3.2.5 on 2024-03-10 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 11, 34, 13, 701871), verbose_name='التاريخ'),
        ),
    ]
