# Generated by Django 3.2.5 on 2024-03-13 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 20, 17, 14, 329746), verbose_name='التاريخ'),
        ),
    ]
