# Generated by Django 3.2.5 on 2024-06-17 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 10, 24, 18, 242197), verbose_name='التاريخ'),
        ),
    ]
