# Generated by Django 3.2.5 on 2024-07-20 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 19, 40, 4, 408159), verbose_name='التاريخ'),
        ),
    ]
