# Generated by Django 3.2.5 on 2024-07-24 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 2, 14, 27, 549419), verbose_name='التاريخ'),
        ),
    ]
