# Generated by Django 3.2.5 on 2024-08-02 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 23, 57, 53, 826764), verbose_name='التاريخ'),
        ),
    ]
