# Generated by Django 3.2.5 on 2024-08-02 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 3, 0, 38, 22, 818344), verbose_name='التاريخ'),
        ),
    ]
