# Generated by Django 3.2.5 on 2024-08-08 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsellers',
            name='initial_balance_type',
            field=models.IntegerField(choices=[(1, 'للعميل'), (2, 'علي العميل')], default=0, verbose_name='نوع القيمة الافتتاحية'),
        ),
        migrations.AlterField(
            model_name='productsellers',
            name='name',
            field=models.CharField(max_length=250, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 14, 8, 12, 867936), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sellerpayments',
            name='paid_type',
            field=models.IntegerField(choices=[(1, 'العميل يدفع لك'), (2, 'أنت تدفع للعميل')], default=0, verbose_name='نوع الدفع'),
        ),
        migrations.AlterField(
            model_name='sellerpayments',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsellers', verbose_name='العميل'),
        ),
    ]
