# Generated by Django 3.2.5 on 2024-08-08 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_auto_20240808_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 20, 48, 1, 240637), verbose_name='التاريخ'),
        ),
    ]
