# Generated by Django 3.2.5 on 2024-08-08 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0026_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 21, 54, 31, 476130), verbose_name='التاريخ'),
        ),
    ]
