# Generated by Django 3.2.5 on 2024-08-09 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0029_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 16, 29, 22, 926699), verbose_name='التاريخ'),
        ),
    ]
