# Generated by Django 3.2.5 on 2024-09-02 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0031_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 2, 23, 21, 16, 328180), verbose_name='التاريخ'),
        ),
    ]
