# Generated by Django 3.2.5 on 2024-09-03 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0032_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 3, 15, 12, 49, 935872), verbose_name='التاريخ'),
        ),
    ]
